add retry, circuitbreaker, and metric
bukalapak/mgo pull request #4
Opened 2018-07-13 10:57 UTC by davidchrisx

2018-07-13 11:16 UTC, reza-putra requested changes

2018-07-13 11:16 UTC, evo3cx commented on backoff.go
> +func newConstantBackoff() constantBackoff {
ini backoff nya sama seperti espeon? kenapa ga pakai espeon aja yah?

https://github.com/bukalapak/espeon#backoff

2018-07-13 11:16 UTC, evo3cx commented on session.go
> +	if len(temp) > 0 {
kenapa param temp nya perlu array yah??
yang di gunakan cuman index zero?

2018-07-13 11:16 UTC, evo3cx commented on socket.go
> +			fmt.Println(len(ops), i)
di hapus saja.

2018-07-13 11:16 UTC, evo3cx commented on socket.go
> +			time.Sleep(sleep)
slepp nya ga pakai backoff?

2018-07-13 11:16 UTC, evo3cx commented on socket.go
> +	for i := 0; i <= socket.dialInfo.MaxRetry; i++ {
kalo ikutin packen seharusnya maxRetry * placeholder CB = 1x open cb

2018-07-13 11:17 UTC, evo3cx commented
Metrics nya baru di register yah? belum di counter ketika CB open/error ?

2018-07-16 06:39 UTC, davidchrisx commented on session.go
> +	if len(temp) > 0 {
biar bisa optional mas, jadi bisa ga masukin timeout

2018-07-18 07:55 UTC, reza-putra requested changes

2018-07-18 07:55 UTC, evo3cx commented on socket.go
> +		sleep := socket.dialInfo.Intervaler.NextInterval()
ini sleep nya jadi di awal yah? kalo seperti ini bukannya setiap dia mau membuat request dia perlu sleep dulu tanpa peduli request itu berhasil atau tidak?

2018-07-18 08:27 UTC, reza-putra approved these changes

2018-07-19 07:07 UTC, merged

2018-07-19 07:39 UTC, evo3cx commented
Jangan lupa unit test nya yah vid.