add context
bukalapak/mgo pull request #6
Opened 2018-08-20 05:44 UTC by davidchrisx

2018-08-24 08:16 UTC, indrasaputra requested changes

2018-08-24 08:16 UTC, indrasaputra commented on session.go
> +		span.LogEvent("error")
untuk block ini (line 5367-5371), kayaknya banyak yg diulang2. coba dijadikan function sendiri aja gimana? biar ga ngulang2 nulis code nya

2018-09-04 07:36 UTC, reza-putra requested changes

2018-09-04 07:36 UTC, evo3cx commented on session.go
> +	ctx context.Context
ini context nya private??? pass ctx nya gmn yah? 

unit test?

2018-09-07 06:06 UTC, davidchrisx commented on session.go
> +	ctx context.Context
di setiap manggil query ada DialInfo mas  yang bungkus ctx nya

2018-09-12 06:21 UTC, reza-putra requested changes

2018-09-12 06:21 UTC, reza-putra commented on session.go
> +	ctx context.Context
dimana yah vid? saya cek disini tidak ada https://github.com/bukalapak/mgo/blob/ctx/session.go#L2643

sekalian tabahin unit test nya vid

2018-09-20 10:58 UTC, reza-putra approved these changes

2018-09-20 11:01 UTC, merged